print("hello player,what is your name?")

user_name=input()
print("   ")
print("hello," + user_name + ",I hope your day is going well.My name is Snoot.I am your virtual game guide.")
print("   ")
print("Now tell me,are you a girl or boy? Or Non-Binary?")
print("   ")
user_name=input()
print("   ")
print("Ah,I see. This is Project:TextToRace ")
print("   ")
answer = input("would you like to start the game? Y or N?(dev note:you cant save your progress this is my first game ;w;)")
print("   ")
print("Lap 21,you are currently driving a race-spec Toyota Supra Mk3 in the World.Improved.Production.Championship. You make your way across the finish line. 11th place. What will you do to overtake the opponent ahead?")
print("   ")
print("1.Make a dive bomb up the inside,2.Try performing a safe overtake at turn 4 or 3. Make a risky overtake on the outside of the faast right-hander.")

answer = input("Type 1,2 or 3 and press enter to do that action.")
print("    ")
if answer == "1":print("You bump into the car in front,but sucessfully pull off the overtake. some damage on your canards though. But you come to finish in 9th place that race.")
if answer == "2":print("You easily pull off the overtake. 10th place! You finish in 8th.")
if answer == "3":print("You try to steer to get through the corner on the outside,but the car understeers and you hit the wall at 200 kph,totalling your car and having a minor injury..")
print("    ")
print("It is the next race,at Willow Springs Raceway in California,U.S.A. You have qualified in 11th place,the green flag waves down and the cars in front speed up. You follow their move as the cars in front go 3-wide into the Castrol corner. A car spins out onto the road,you are about to hit it at 150 kph. ")
print("    ")
print("What will you do?")
print("1.Swerve to the inside of the corner and cut it,risking a penalty or 2.Drive to the outside but risk getting bumped in the back.")
print("    ")
answer = input("Type 1 or 2 and press enter to do that action.")
if answer == "1":print("You swerve and hop over the kerb,you may think it was corner-cutting,but at that moment your car was up in the air. Thus, no penalty.")
if answer == "2":print("You move to the outside,but as you do it,your neck jerks foward but is restrained by the seatbelt and H.A.N.S device. Your rear has fell off and now you have  m u c h  less downforce")